import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const ui={world:$('#world'),start:$('#start'),toast:$('#toast'),overhead:$('#overhead'),cdu:$('#cdu'),pfd:$('#pfd'),nd:$('#nd'),eicas:$('#eicas'),throttle:$('#throttle'),flaps:$('#flaps'),speedbrake:$('#speedbrake'),gear:$('#gearBtn'),sound:$('#soundBtn')};
const saved=JSON.parse(localStorage.getItem('b738-sim-records')||'{"cycles":0,"hours":0,"bestLanding":0}');
const state={running:false,ready:false,external:false,sound:true,battery:false,groundPower:false,apuMaster:false,apuRunning:false,apuGen:false,fuelPumps:false,crossfeed:false,hydraulics:false,packs:false,bleed:false,beacon:false,landingLights:false,engines:[0,0],engineStarting:[false,false],throttle:0,flaps:0,speedbrake:0,gearDown:true,gearWarnUntil:0,ias:0,altitude:0,radioAlt:0,vs:0,heading:0,pitch:0,roll:0,rudder:0,x:0,y:2.8,z:730,weight:65000,fuel:7800,onGround:true,flightSeconds:0,airborne:false,route:[],activeLeg:0,ap:{fd:false,at:false,lnav:false,vnav:false,heading:false,altitude:false,ap:false,app:false},targets:{speed:250,heading:360,altitude:10000}};
const keys={};let last=performance.now(),audio=null,engineGain=null,warningTimer=0,tutorialIndex=0,tutorialActive=false,tutorialKind='startup';

const scene=new THREE.Scene();scene.background=new THREE.Color(0x8ccbea);scene.fog=new THREE.Fog(0x8ccbea,900,9500);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,14000);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;ui.world.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xdff5ff,0x667453,2.4));const sun=new THREE.DirectionalLight(0xfff2d1,2.3);sun.position.set(-800,1200,500);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(18000,18000),new THREE.MeshStandardMaterial({color:0x607c49,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const runway=new THREE.Group();const asphalt=new THREE.Mesh(new THREE.BoxGeometry(68,.25,2600),new THREE.MeshStandardMaterial({color:0x35393b,roughness:1}));asphalt.receiveShadow=true;runway.add(asphalt);for(let z=-1190;z<1200;z+=65){const m=new THREE.Mesh(new THREE.BoxGeometry(2,.08,28),new THREE.MeshBasicMaterial({color:0xf4f1df}));m.position.set(0,.18,z);runway.add(m)}for(const x of[-31,31])for(let z=-1250;z<=1250;z+=45){const light=new THREE.Mesh(new THREE.SphereGeometry(.28,6,4),new THREE.MeshBasicMaterial({color:0xffffff}));light.position.set(x,.35,z);runway.add(light)}runway.position.z=-500;scene.add(runway);
const terminal=new THREE.Mesh(new THREE.BoxGeometry(700,42,150),new THREE.MeshStandardMaterial({color:0x9ba7aa,roughness:.7}));terminal.position.set(390,21,-1340);scene.add(terminal);
for(let i=0;i<70;i++){const h=12+Math.random()*55,b=new THREE.Mesh(new THREE.BoxGeometry(25+Math.random()*45,h,25+Math.random()*45),new THREE.MeshStandardMaterial({color:0x88918c,roughness:1}));b.position.set((Math.random()-.5)*3500,h/2,-1800-Math.random()*3500);scene.add(b)}
// Ground detail and clouds make altitude and speed readable.
const fieldColors=[0x73884f,0x8c9450,0x667f47,0x9a8e55];for(let i=0;i<64;i++){const field=new THREE.Mesh(new THREE.PlaneGeometry(240+Math.random()*520,180+Math.random()*420),new THREE.MeshStandardMaterial({color:fieldColors[i%fieldColors.length],roughness:1}));field.rotation.x=-Math.PI/2;field.position.set((Math.random()-.5)*9000,.035,-500-Math.random()*8500);scene.add(field)}
const roadMat=new THREE.MeshStandardMaterial({color:0x77786e,roughness:1});for(const x of[-1450,1550]){const road=new THREE.Mesh(new THREE.BoxGeometry(18,.08,9000),roadMat);road.position.set(x,.05,-3500);scene.add(road)}
const cloudGeo=new THREE.SphereGeometry(1,10,7),cloudMat=new THREE.MeshLambertMaterial({color:0xffffff,transparent:true,opacity:.72});for(let i=0;i<28;i++){const cloud=new THREE.Group(),size=20+Math.random()*38;for(let j=0;j<4;j++){const puff=new THREE.Mesh(cloudGeo,cloudMat);puff.scale.set(size*(.7+Math.random()*.6),size*(.22+Math.random()*.16),size*(.45+Math.random()*.4));puff.position.set((j-1.5)*size*.55,Math.random()*size*.12,Math.random()*size*.25);cloud.add(puff)}cloud.position.set((Math.random()-.5)*8000,420+Math.random()*650,-800-Math.random()*8000);scene.add(cloud)}

// 737-800-inspired proportions: rounded radome, swept wings, low nacelles and tall fin.
const aircraft=new THREE.Group();const bodyMat=new THREE.MeshStandardMaterial({color:0xf3f4f5,roughness:.42,metalness:.08}),redMat=new THREE.MeshStandardMaterial({color:0xb51f2d,roughness:.5}),goldMat=new THREE.MeshStandardMaterial({color:0xe1aa22,roughness:.48}),darkMat=new THREE.MeshStandardMaterial({color:0x111a20,roughness:.3}),engineMat=new THREE.MeshStandardMaterial({color:0xdfe3e4,roughness:.38,metalness:.18}),rubberMat=new THREE.MeshStandardMaterial({color:0x101112,roughness:.9});
const fuselage=new THREE.Mesh(new THREE.CylinderGeometry(1.86,1.86,31.5,32),bodyMat);fuselage.rotation.x=Math.PI/2;fuselage.position.z=.8;aircraft.add(fuselage);const nose=new THREE.Mesh(new THREE.SphereGeometry(1.87,32,18),bodyMat);nose.scale.set(1,1,.72);nose.position.z=-15.15;aircraft.add(nose);const tailCone=new THREE.Mesh(new THREE.ConeGeometry(1.84,6.2,32),bodyMat);tailCone.rotation.x=-Math.PI/2;tailCone.position.z=19.65;aircraft.add(tailCone);
for(const side of[-1,1]){for(let z=-10.5;z<13.5;z+=1.25){const win=new THREE.Mesh(new THREE.BoxGeometry(.035,.25,.48),darkMat);win.position.set(side*1.855,.55,z);aircraft.add(win)}const cockpitWindow=new THREE.Mesh(new THREE.BoxGeometry(.055,.62,1.5),darkMat);cockpitWindow.position.set(side*1.66,.72,-14.35);cockpitWindow.rotation.y=side*.34;aircraft.add(cockpitWindow);const stripe=new THREE.Mesh(new THREE.BoxGeometry(.045,.16,25),goldMat);stripe.position.set(side*1.87,.08,.3);aircraft.add(stripe)}
function horizontalSurface(points,material,y){const verts=[];for(let i=1;i<points.length-1;i++)verts.push(...points[0],...points[i],...points[i+1]);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geometry.computeVertexNormals();const mesh=new THREE.Mesh(geometry,material);mesh.position.y=y;aircraft.add(mesh);return mesh}
horizontalSurface([[-1.3,0,-3.8],[-18,0,4.9],[-17.2,0,7.2],[-2,0,3.1],[2,0,3.1],[17.2,0,7.2],[18,0,4.9],[1.3,0,-3.8]],bodyMat,.05);horizontalSurface([[-.7,0,14.3],[-6.8,0,18],[-6.5,0,19.2],[0,0,17.5],[6.5,0,19.2],[6.8,0,18],[.7,0,14.3]],bodyMat,.7);
const finGeo=new THREE.BufferGeometry();finGeo.setAttribute('position',new THREE.Float32BufferAttribute([-.12,0,14.8,.12,0,14.8,-.12,6.8,19,.12,0,14.8,.12,6.8,19,-.12,6.8,19],3));finGeo.computeVertexNormals();aircraft.add(new THREE.Mesh(finGeo,redMat));for(const x of[-5.2,5.2]){const nacelle=new THREE.Mesh(new THREE.CylinderGeometry(.92,1.04,3.65,24),engineMat);nacelle.rotation.x=Math.PI/2;nacelle.position.set(x,-1.35,-1.3);aircraft.add(nacelle);const fan=new THREE.Mesh(new THREE.CircleGeometry(.88,24),darkMat);fan.position.set(x,-1.35,-3.14);fan.rotation.x=-Math.PI/2;aircraft.add(fan);const pylon=new THREE.Mesh(new THREE.BoxGeometry(.38,1.15,2.5),bodyMat);pylon.position.set(x,-.55,-.25);pylon.rotation.x=-.12;aircraft.add(pylon)}
const landingGear=new THREE.Group();for(const [x,z] of[[-3.1,2.6],[3.1,2.6],[0,-12.8]]){const strut=new THREE.Mesh(new THREE.CylinderGeometry(.09,.09,2.2,8),darkMat);strut.position.set(x,-2,z);landingGear.add(strut);const wheel=new THREE.Mesh(new THREE.TorusGeometry(.38,.16,8,14),rubberMat);wheel.rotation.y=Math.PI/2;wheel.position.set(x,-3.05,z);landingGear.add(wheel)}aircraft.add(landingGear);aircraft.userData.landingGear=landingGear;aircraft.scale.set(.92,.92,.92);scene.add(aircraft);

function toast(message){ui.toast.textContent=message;ui.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('show'),2200)}
function initAudio(){if(audio)return;audio=new(window.AudioContext||window.webkitAudioContext)();const osc=audio.createOscillator(),filter=audio.createBiquadFilter();engineGain=audio.createGain();osc.type='sawtooth';osc.frequency.value=42;filter.type='lowpass';filter.frequency.value=130;engineGain.gain.value=0;osc.connect(filter).connect(engineGain).connect(audio.destination);osc.start()}
function beep(freq=740,duration=.12){if(!state.sound)return;initAudio();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.08,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
function powered(){return state.battery||state.groundPower||state.apuGen||state.engines.some(n=>n>55)}
function toggleSystem(name,button){state[name]=!state[name];button.classList.toggle('on',state[name]);button.textContent=button.textContent.replace(/ ON| OFF/g,'')+(state[name]?' ON':' OFF');if(name==='apuMaster'&&!state.apuMaster){state.apuRunning=false;state.apuGen=false}refreshChecklist();beep(520,.05)}
function startAPU(){if(!state.battery||!state.apuMaster||!state.fuelPumps){toast('APU START 需要 BATTERY、APU MASTER 和 FUEL PUMPS');return}if(state.apuRunning)return;toast('APU 正在启动…');const b=$('[data-action="apuStart"]');b.classList.add('start');setTimeout(()=>{state.apuRunning=true;b.classList.remove('start');b.classList.add('on');b.textContent='APU RUNNING';toast('APU 可用');beep(880,.18);refreshChecklist()},3200)}
function startEngine(index){if(!state.apuRunning||!state.bleed||!state.fuelPumps){toast('发动机启动需要 APU RUNNING、APU BLEED 和 FUEL PUMPS');return}if(state.engineStarting[index]||state.engines[index]>50)return;state.engineStarting[index]=true;toast(`ENGINE ${index+1} START`);const timer=setInterval(()=>{state.engines[index]=Math.min(64,state.engines[index]+3);if(state.engines[index]>=60){clearInterval(timer);state.engineStarting[index]=false;state.engines[index]=60;toast(`ENGINE ${index+1} STABLE`);beep(940,.13);refreshChecklist()}},140)}
function setReady(){Object.assign(state,{battery:true,groundPower:false,apuMaster:true,apuRunning:true,apuGen:true,fuelPumps:true,hydraulics:true,packs:true,bleed:true,beacon:true,engines:[60,60],ready:true});$$('[data-switch]').forEach(b=>{const n=b.dataset.switch;b.classList.toggle('on',!!state[n])});$('[data-action="apuStart"]').classList.add('on');$('[data-action="apuStart"]').textContent='APU RUNNING';refreshChecklist()}
function refreshChecklist(){const values={battery:state.battery,ground:state.groundPower||state.apuGen||state.engines.some(n=>n>55),apu:state.apuRunning,fuel:state.fuelPumps,engines:state.engines.every(n=>n>55),hydraulics:state.hydraulics};$$('.check').forEach(row=>{const ok=values[row.dataset.check];row.classList.toggle('done',ok);row.querySelector('b').textContent=ok?'ON':'OFF'})}
async function enterFullscreen(){if(document.fullscreenElement)return;try{await document.documentElement.requestFullscreen()}catch{toast('浏览器阻止了自动全屏，请点击右上角“全屏”')}}
function begin(quick){initAudio();state.running=true;ui.start.classList.add('hidden');enterFullscreen();if(quick)setReady();toast(quick?'飞机已在跑道就绪':'从顶板开始：BATTERY → GROUND POWER → APU');}

const tutorialSteps=[
  {title:'打开顶板',text:'737 的冷舱启动从头顶面板开始。这里负责电源、燃油、引气、液压和灯光。',target:'#overheadBtn',done:()=>ui.overhead.classList.contains('open'),prepare:()=>ui.overhead.classList.remove('open')},
  {title:'接通电瓶',text:'点击 BATTERY。电瓶为基础控制和备用系统供电，是冷舱启动的第一步。',target:'[data-switch="battery"]',done:()=>state.battery},
  {title:'接通地面电源',text:'点击 GROUND POWER，让飞机在发动机未启动时获得稳定交流电。仪表随后会点亮。',target:'[data-switch="groundPower"]',done:()=>state.groundPower},
  {title:'开启燃油泵',text:'点击 FUEL PUMPS。APU 和发动机启动前必须保证燃油供应。',target:'[data-switch="fuelPumps"]',done:()=>state.fuelPumps},
  {title:'启动 APU',text:'先打开 APU MASTER，再点击 APU START。等待约 3 秒，按钮显示 APU RUNNING。',target:'[data-switch="apuMaster"]',done:()=>state.apuRunning},
  {title:'建立引气',text:'APU 运转后点击 APU BLEED。引气提供发动机启动所需的压缩空气。',target:'[data-switch="bleed"]',done:()=>state.bleed},
  {title:'启动双发',text:'依次点击 ENGINE 1 和 ENGINE 2，等待两台发动机稳定到 60%。',target:'[data-action="startEng1"]',done:()=>state.engines.every(n=>n>55)},
  {title:'接通液压',text:'点击 HYD PUMPS。没有液压，主要飞行操纵面无法正常工作。',target:'[data-switch="hydraulics"]',done:()=>state.hydraulics},
  {title:'设置起飞襟翼',text:'把右下角 FLAPS 拉到 5。襟翼增加低速升力，缩短起飞距离。',target:'#flaps',done:()=>state.flaps>=2,prepare:()=>ui.overhead.classList.remove('open')},
  {title:'起飞',text:'把 THRUST 推到 TO/GA。速度超过约 118 节后按住 W 抬头；正上升后按 G 收起落架。',target:'#throttle',done:()=>state.airborne&&state.altitude>100}
];
const closePopups=()=>{ui.overhead.classList.remove('open');ui.cdu.classList.remove('open')};
const panelTutorialSteps=[
  {title:'欢迎来到 737-800 驾驶舱',text:'这次导览只讲面板，不要求你操作。高亮区域就是当前讲解对象；看完后点击“下一步”。',target:'#mainPanel',prepare:closePopups},
  {title:'MCP 模式控制面板',text:'MCP 用来选择自动驾驶的速度、航向和高度。IAS、HDG、ALTITUDE 是目标值；LNAV/VNAV 管理航路与垂直剖面，CMD A 接通自动驾驶。',target:'#mcpPanel',prepare:closePopups},
  {title:'PFD 主飞行显示器',text:'左侧数字是飞机速度 IAS，单位是节（KT）；右侧是高度。中央蓝棕地平仪显示俯仰和滚转，顶部绿色文字显示自动飞行模式。',target:'#pfdPanel',prepare:closePopups},
  {title:'ND 导航显示器',text:'ND 显示航向、航路点和当前航段。执行 CDU 航路并接通 LNAV 后，飞机会追踪地图上的航线。底部 GS 是地速，单位同样是节。',target:'#ndPanel',prepare:closePopups},
  {title:'发动机显示',text:'这里的大数字约 60 或 61 是发动机 N1 转速百分比，不是飞机速度。真正速度请看左侧 PFD 的 IAS。下面还能看到 EGT、燃油、襟翼和起落架状态。',target:'#eicasPanel',prepare:closePopups},
  {title:'警告系统',text:'FIRE WARN 是火警，MASTER CAUTION 是主警戒。亮起时先识别故障来源，再处理对应系统；它们不是普通状态灯。',target:'#warningsPanel',prepare:closePopups},
  {title:'驾驶盘 Yoke',text:'按 W/S 控制俯仰，按 A/D 控制滚转，驾驶盘会跟随滚转输入转动。Q/E 控制方向舵，主要用于地面和协调偏航。',target:'#yokePanel',prepare:closePopups},
  {title:'中央操纵区',text:'SPD BRK 是减速板，THRUST 是油门，FLAPS 是襟翼，GEAR 控制起落架。起飞常用襟翼 5、油门 TO/GA，离地并确认正上升后收轮。',target:'#controlsPanel',prepare:closePopups},
  {title:'Overhead 顶板',text:'顶板管理电源、APU、燃油、引气、液压和灯光。冷舱启动大多从这里开始；关闭关键系统会直接影响仪表和飞机状态。',target:'#overhead',prepare:()=>{ui.cdu.classList.remove('open');ui.overhead.classList.add('open')}},
  {title:'CDU / FMC',text:'CDU 用来输入起点、终点和航路点。点击 EXECUTE ROUTE 后航路写入 ND，并预位 LNAV。后续版本会继续加入 SID、STAR、性能页和进近。',target:'#cdu',prepare:()=>{ui.overhead.classList.remove('open');ui.cdu.classList.add('open')}},
  {title:'导览完成',text:'现在你已经知道速度在哪里看，也能分清 MCP、飞行仪表、发动机屏、中央操纵区、顶板和 CDU。接下来建议打开“启动教学”完成一次冷舱启动。',target:'#tutorialBtn',prepare:closePopups}
];
function activeTutorialSteps(){return tutorialKind==='panels'?panelTutorialSteps:tutorialSteps}
function clearTutorialTarget(){$$('.tutorial-target').forEach(e=>e.classList.remove('tutorial-target'))}
function placeTutorial(target){const card=$('#tutorial');card.style.top='';card.style.bottom='';card.style.left='50%';card.style.right='auto';card.style.transform='translateX(-50%)';if(!target)return;const r=target.getBoundingClientRect();if(r.top<innerHeight*.5){card.style.top='auto';card.style.bottom='18px'}else{card.style.top='75px';card.style.bottom='auto'}if(innerWidth>900&&r.left<innerWidth*.38){card.style.left='auto';card.style.right='18px';card.style.transform='none'}else if(innerWidth>900&&r.right>innerWidth*.62){card.style.left='18px';card.style.right='auto';card.style.transform='none'}}
function showTutorialStep(){clearTutorialTarget();const steps=activeTutorialSteps(),step=steps[tutorialIndex];if(!step){finishTutorial();return}step.prepare?.();const informational=tutorialKind==='panels';$('#tutorialProgress').textContent=`${informational?'驾驶舱面板导览':'冷舱启动教学'} ${tutorialIndex+1} / ${steps.length}`;$('#tutorialTitle').textContent=step.title;$('#tutorialText').textContent=step.text;$('#tutorialBack').disabled=tutorialIndex===0;$('#tutorialNext').classList.toggle('active',informational||step.done());$('#tutorialNext').textContent=tutorialIndex===steps.length-1?'完成':'下一步';const target=$(step.target);target?.classList.add('tutorial-target');placeTutorial(target);$('#tutorialHint').textContent=informational?'阅读后点击下一步':step.done()?'已完成 ✓':'等待你完成操作…'}
function beginTutorial(kind){tutorialKind=kind;if(!state.running)begin(kind==='panels');tutorialActive=true;tutorialIndex=0;$('#tutorial').classList.remove('hidden');document.body.classList.remove('view-external');state.external=false;showTutorialStep()}
function startTutorial(){beginTutorial('startup')}
function startPanelTour(){beginTutorial('panels')}
function finishTutorial(){const panels=tutorialKind==='panels';tutorialActive=false;clearTutorialTarget();closePopups();$('#tutorial').classList.add('hidden');toast(panels?'驾驶舱面板导览完成！':'冷舱启动教学完成！');localStorage.setItem(panels?'b738-panel-tour-complete':'b738-tutorial-complete','1')}
function monitorTutorial(){if(!tutorialActive||tutorialKind==='panels')return;const step=activeTutorialSteps()[tutorialIndex];if(step?.done()){$('#tutorialHint').textContent='已完成 ✓';$('#tutorialNext').classList.add('active')}}

$$('[data-switch]').forEach(b=>b.addEventListener('click',()=>toggleSystem(b.dataset.switch,b)));$('[data-action="apuStart"]').onclick=startAPU;$('[data-action="startEng1"]').onclick=()=>startEngine(0);$('[data-action="startEng2"]').onclick=()=>startEngine(1);
$('#panelTourStart').onclick=startPanelTour;$('#tutorialStart').onclick=startTutorial;$('#coldStart').onclick=()=>begin(false);$('#quickStart').onclick=()=>begin(true);$('#overheadBtn').onclick=()=>ui.overhead.classList.toggle('open');$('#cduBtn').onclick=()=>ui.cdu.classList.toggle('open');
$('#panelTourBtn').onclick=startPanelTour;$('#tutorialBtn').onclick=startTutorial;$('#tutorialClose').onclick=()=>{tutorialActive=false;clearTutorialTarget();closePopups();$('#tutorial').classList.add('hidden')};$('#tutorialBack').onclick=()=>{tutorialIndex=Math.max(0,tutorialIndex-1);showTutorialStep()};$('#tutorialNext').onclick=()=>{const step=activeTutorialSteps()[tutorialIndex];if(step.done&&!step.done()){toast('请先完成当前教学操作');return}tutorialIndex++;showTutorialStep()};
$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():enterFullscreen();document.addEventListener('fullscreenchange',()=>{$('#fullscreenBtn').textContent=document.fullscreenElement?'退出全屏':'全屏'});
$('#viewBtn').onclick=()=>{state.external=!state.external;document.body.classList.toggle('view-external',state.external);$('#viewBtn').textContent=state.external?'驾驶舱视角':'外部视角'};
ui.sound.onclick=()=>{state.sound=!state.sound;ui.sound.textContent=`声音 ${state.sound?'ON':'OFF'}`;ui.sound.classList.toggle('active',state.sound);if(engineGain&&!state.sound)engineGain.gain.value=0};
ui.throttle.oninput=()=>{state.throttle=+ui.throttle.value;$('#throttleVal').textContent=state.throttle>90?'TO/GA':state.throttle+'%'};ui.flaps.oninput=()=>{state.flaps=+ui.flaps.value;$('#flapsVal').textContent=state.flaps?['','1','5','15','30','40'][state.flaps]:'UP'};ui.speedbrake.oninput=()=>{state.speedbrake=+ui.speedbrake.value;$('#speedbrakeVal').textContent=state.speedbrake>75?'UP':state.speedbrake?'ARMED':'DOWN'};ui.gear.onclick=()=>{if(state.onGround&&state.gearDown){state.gearWarnUntil=performance.now()+2600;toast('GEAR LEVER LOCKED · 地面禁止收轮');beep(245,.65);return}state.gearDown=!state.gearDown;ui.gear.classList.toggle('down',state.gearDown);ui.gear.innerHTML=`GEAR<br>${state.gearDown?'DOWN':'UP'}`;aircraft.userData.landingGear.visible=state.gearDown;beep(430,.12)};
$$('[data-ap]').forEach(b=>b.onclick=()=>{const n=b.dataset.ap;if(n==='ap'&&!state.engines.every(v=>v>50)){toast('CMD A 不可用：发动机未运行');return}state.ap[n]=!state.ap[n];b.classList.toggle('on',state.ap[n]);beep(state.ap[n]?900:480,.08)});
['mcpSpeed','mcpHeading','mcpAltitude'].forEach(id=>$('#'+id).onchange=()=>{const k=id.replace('mcp','').toLowerCase();state.targets[k]=+$('#'+id).value});
const waypointMap={PEK:[0,-2200],ANDAN:[600,-3800],OLNEX:[-500,-5600],SASAN:[0,-7600]};
$('#execRoute').onclick=()=>{const names=$('#route').value.toUpperCase().split(',').map(v=>v.trim()).filter(Boolean);state.route=names.map((name,i)=>({name,pos:waypointMap[name]||[(i%2?1:-1)*500,-2200-i*1600]}));state.activeLeg=0;$('#legs').textContent=`${$('#origin').value.toUpperCase()} → ${names.join(' → ')} → ${$('#destination').value.toUpperCase()}\nACTIVATE / EXECUTED`;state.ap.lnav=true;$('[data-ap="lnav"]').classList.add('on');toast('航路已执行，LNAV ARM');beep(1000,.12)};

addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key.toLowerCase()==='g')ui.gear.click();if(e.key.toLowerCase()==='v')$('#viewBtn').click();if(e.key.toLowerCase()==='f'){ui.flaps.value=Math.min(5,+ui.flaps.value+1);ui.flaps.oninput()}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);

function flightPhysics(dt){const running=state.engines.reduce((a,b)=>a+b,0)/120;const n1=running*(22+state.throttle*.78);const drag=0.011*state.ias+state.flaps*1.1+(state.gearDown?3.2:0)+state.speedbrake*.045;let accel=n1*.082-drag-1.1;if(state.onGround&&state.ias<4&&state.throttle<8)accel=-state.ias;state.ias=Math.max(0,state.ias+accel*dt);
  let pitchInput=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0),rollInput=(keys.a||keys.arrowleft?-1:0)+(keys.d||keys.arrowright?1:0),rudderInput=(keys.q?-1:0)+(keys.e?1:0);
  if(state.ap.ap){if(state.ap.heading||state.ap.lnav){let target=state.targets.heading;if(state.ap.lnav&&state.route.length){const leg=state.route[state.activeLeg],dx=leg.pos[0]-state.x,dz=leg.pos[1]-state.z;target=(Math.atan2(dx,-dz)*180/Math.PI+360)%360;if(Math.hypot(dx,dz)<240&&state.activeLeg<state.route.length-1)state.activeLeg++}let delta=((target-state.heading+540)%360)-180;rollInput=THREE.MathUtils.clamp(delta/22,-1,1)}if(state.ap.altitude||state.ap.vnav){const err=state.targets.altitude-state.altitude;pitchInput=THREE.MathUtils.clamp(err/1800-state.vs/3500,-.55,.75)}if(state.ap.at){const err=state.targets.speed-state.ias;state.throttle=THREE.MathUtils.clamp(state.throttle+err*.04*dt,0,100);ui.throttle.value=state.throttle}}
  state.roll+=((rollInput*28)-state.roll)*Math.min(1,dt*2.2);state.pitch+=((pitchInput*12)-state.pitch)*Math.min(1,dt*1.8);state.rudder+=(rudderInput-state.rudder)*Math.min(1,dt*2.5);document.documentElement.style.setProperty('--yoke-roll',`${state.roll*.8}deg`);
  const rotateRate=(state.roll*.11+state.rudder*2.5)*Math.min(1,state.ias/90);state.heading=(state.heading+rotateRate*dt+360)%360;const flapLift=state.flaps*1.3;const liftFactor=Math.max(0,(state.ias-105+flapLift*5)/80);state.vs=(state.pitch*155+flapLift*80-220+liftFactor*210)-(state.speedbrake*7);if(state.onGround){if(state.ias>118&&state.pitch>4){state.onGround=false;state.airborne=true;state.y=3.2;toast('POSITIVE RATE');beep(900,.1)}else{state.vs=0;state.altitude=0;state.y=2.8}}
  if(!state.onGround){state.altitude=Math.max(0,state.altitude+state.vs/60*dt);state.y=2.8+state.altitude*.3048;if(state.altitude<=0){const safe=state.ias<155&&Math.abs(state.vs)<650&&state.gearDown;state.onGround=true;state.y=2.8;if(state.airborne){state.airborne=false;saved.cycles++;const landing=Math.round(Math.abs(state.vs));saved.bestLanding=saved.bestLanding?Math.min(saved.bestLanding,landing):landing;localStorage.setItem('b738-sim-records',JSON.stringify(saved));toast(safe?`着陆完成 · ${landing} ft/min`:'重着陆警告');beep(safe?620:250,safe?.18:.7)}}}
  const rad=state.heading*Math.PI/180,speedM=state.ias*.5144;state.x+=Math.sin(rad)*speedM*dt;state.z-=Math.cos(rad)*speedM*dt;state.flightSeconds+=dt;saved.hours+=dt/3600;if(Math.floor(state.flightSeconds)%30===0)localStorage.setItem('b738-sim-records',JSON.stringify(saved));aircraft.position.set(state.x,state.y,state.z);aircraft.rotation.set(state.pitch*Math.PI/180,rad,state.roll*-Math.PI/180);
  if(state.radioAlt<500&&!state.gearDown&&!state.onGround&&performance.now()-warningTimer>3000){toast('TOO LOW — GEAR');beep(260,.55);warningTimer=performance.now()}if(engineGain&&state.sound)engineGain.gain.value=running*(.015+state.throttle*.0005);
}

function fitCanvas(c){const dpr=Math.min(devicePixelRatio,2),w=c.clientWidth,h=c.clientHeight;if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr}const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);return{x,w,h}}
function drawPFD(){const{x,w,h}=fitCanvas(ui.pfd);x.clearRect(0,0,w,h);if(!powered()){x.fillStyle='#080909';x.fillRect(0,0,w,h);x.fillStyle='#ff8b25';x.font='12px Consolas';x.fillText('DISPLAY SOURCE',w/2-48,h/2);return}x.save();x.translate(w/2,h/2);x.rotate(-state.roll*Math.PI/180);const py=state.pitch*3;x.fillStyle='#1987bc';x.fillRect(-w,-h*2+py,w*2,h*2);x.fillStyle='#7d5032';x.fillRect(-w,py,w*2,h*2);x.strokeStyle='#fff';x.lineWidth=2;x.beginPath();x.moveTo(-w,py);x.lineTo(w,py);x.stroke();for(let p=-20;p<=20;p+=5){if(!p)continue;const yy=py-p*3;x.lineWidth=1;x.beginPath();x.moveTo(-20,yy);x.lineTo(20,yy);x.stroke();x.fillStyle='#fff';x.font='9px Consolas';x.fillText(Math.abs(p),24,yy+3)}x.restore();x.strokeStyle='#fff';x.lineWidth=3;x.beginPath();x.moveTo(w/2-28,h/2);x.lineTo(w/2-8,h/2);x.lineTo(w/2,h/2+7);x.lineTo(w/2+8,h/2);x.lineTo(w/2+28,h/2);x.stroke();x.fillStyle='#111d';x.fillRect(0,0,52,h);x.fillRect(w-59,0,59,h);x.fillStyle='#fff';x.font='bold 17px Consolas';x.fillText(Math.round(state.ias),9,h/2+5);x.fillText(Math.round(state.altitude),w-55,h/2+5);x.fillStyle='#71e77b';x.font='bold 11px Consolas';const modes=[state.ap.at?'MCP SPD':'',state.ap.lnav?'LNAV':state.ap.heading?'HDG SEL':'',state.ap.vnav?'VNAV PTH':state.ap.altitude?'ALT HOLD':''];x.fillText(modes.join('   '),8,14);x.fillStyle='#fff';x.font='10px Consolas';x.fillText(`V/S ${Math.round(state.vs)}`,w-70,h-10);x.fillText(`HDG ${String(Math.round(state.heading)).padStart(3,'0')}`,w/2-28,h-8)}
function drawND(){const{x,w,h}=fitCanvas(ui.nd);x.fillStyle='#020506';x.fillRect(0,0,w,h);if(!powered()){x.fillStyle='#ff8b25';x.font='12px Consolas';x.fillText('MAP',w/2-12,h/2);return}const cx=w/2,cy=h*.82,range=9260,scale=Math.min(w*.46,h*.72)/range,angle=-state.heading*Math.PI/180;x.save();x.beginPath();x.rect(0,20,w,h-38);x.clip();x.strokeStyle='#31514f';x.lineWidth=1;for(const f of[.25,.5,.75,1]){x.beginPath();x.arc(cx,cy,range*scale*f,Math.PI,Math.PI*2);x.stroke();x.fillStyle='#748580';x.font='9px Consolas';x.fillText((5*f).toFixed(f===1?0:1),cx+4,cy-range*scale*f+10)}for(let deg=-60;deg<=60;deg+=30){const a=(deg-90)*Math.PI/180,r=range*scale;x.beginPath();x.moveTo(cx+Math.cos(a)*(r-7),cy+Math.sin(a)*(r-7));x.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);x.stroke()}const project=(px,pz)=>{const dx=px-state.x,dz=pz-state.z;return[cx+(dx*Math.cos(angle)-dz*Math.sin(angle))*scale,cy+(dx*Math.sin(angle)+dz*Math.cos(angle))*scale]};const runwayPts=[[-34,-1800],[34,-1800],[34,800],[-34,800]].map(p=>project(...p));x.strokeStyle='#fff';x.beginPath();runwayPts.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.closePath();x.stroke();if(state.route.length){x.strokeStyle='#d84de8';x.lineWidth=2;x.beginPath();state.route.forEach((leg,i)=>{const p=project(...leg.pos);i?x.lineTo(...p):x.moveTo(cx,cy)});x.stroke()}state.route.forEach((leg,i)=>{const[px,py]=project(...leg.pos);if(px>8&&px<w-8&&py>22&&py<h-18){x.strokeStyle=i===state.activeLeg?'#ff4cff':'#42d9ff';x.lineWidth=2;x.beginPath();x.moveTo(px,py-5);x.lineTo(px+5,py);x.lineTo(px,py+5);x.lineTo(px-5,py);x.closePath();x.stroke();x.fillStyle=i===state.activeLeg?'#ff7cff':'#42d9ff';x.font='10px Consolas';x.fillText(leg.name,px+7,py+3)}});x.restore();x.strokeStyle='#fff';x.lineWidth=2;x.beginPath();x.moveTo(cx,cy-9);x.lineTo(cx-6,cy+8);x.lineTo(cx,cy+5);x.lineTo(cx+6,cy+8);x.closePath();x.stroke();x.fillStyle='#71e77b';x.font='bold 11px Consolas';x.fillText(state.ap.lnav?'LNAV ACTIVE':'MAP / TRACK UP',8,14);x.fillStyle='#fff';x.fillText(`GS ${Math.round(state.ias)} KT`,8,h-6);x.fillText(`TRK ${String(Math.round(state.heading)).padStart(3,'0')}°`,w/2-28,14);x.fillText('RANGE 5 NM',w-75,h-6);const next=state.route[state.activeLeg];if(next){const distance=Math.hypot(next.pos[0]-state.x,next.pos[1]-state.z)/1852;x.fillStyle='#ff7cff';x.fillText(`${next.name}  ${distance.toFixed(1)} NM`,w-95,14)}}
function drawEICAS(){const{x,w,h}=fitCanvas(ui.eicas);x.fillStyle='#020505';x.fillRect(0,0,w,h);if(!powered()){x.fillStyle='#ff8b25';x.font='11px Consolas';x.fillText('ENG DISPLAY',w/2-38,h/2);return}x.fillStyle='#fff';x.font='10px Consolas';x.fillText('N1',w/2-7,15);state.engines.forEach((base,i)=>{const n=base?Math.min(101,22+state.throttle*.78):0,cx=i?w*.72:w*.28,cy=55,r=27;x.strokeStyle='#55615c';x.lineWidth=4;x.beginPath();x.arc(cx,cy,r,.7*Math.PI,2.3*Math.PI);x.stroke();x.strokeStyle=n>95?'#ff4d3d':'#72e57b';x.beginPath();x.arc(cx,cy,r,.7*Math.PI,(.7+1.6*n/100)*Math.PI);x.stroke();x.fillStyle='#fff';x.font='bold 13px Consolas';x.fillText(n.toFixed(1),cx-18,cy+5);x.fillStyle='#72e57b';x.font='10px Consolas';x.fillText(`EGT ${Math.round(n*7.4)}`,cx-23,105)});x.fillStyle='#fff';x.fillText(`FUEL ${Math.round(state.fuel)} KG`,12,h-22);x.fillText(`FLAPS ${state.flaps?['','1','5','15','30','40'][state.flaps]:'UP'}`,12,h-8);x.fillText(`GEAR ${state.gearDown?'DOWN':'UP'}`,w-72,h-8)}
function updateWarnings(){const caution=state.running&&(!powered()||state.engines.some(n=>state.ready&&n<20)||(!state.hydraulics&&state.engines.some(n=>n>50))||performance.now()<state.gearWarnUntil);$('#masterCaution').classList.toggle('lit',caution);$('#fireWarn').classList.toggle('lit',state.engines.some(n=>n>103))}
function renderView(){const rad=state.heading*Math.PI/180;if(state.external){const distance=state.onGround?62:88,height=state.onGround?24:36;const behind=new THREE.Vector3(state.x-Math.sin(rad)*distance,state.y+height,state.z+Math.cos(rad)*distance);camera.position.lerp(behind,.08);camera.lookAt(state.x,state.y,state.z)}else{camera.position.set(state.x,state.y+2.7,state.z-1.8);const look=new THREE.Vector3(state.x+Math.sin(rad)*500,state.y+2.7+Math.tan(state.pitch*Math.PI/180)*500,state.z-Math.cos(rad)*500);camera.up.set(Math.sin(state.roll*Math.PI/180),Math.cos(state.roll*Math.PI/180),0);camera.lookAt(look)}aircraft.visible=state.external;renderer.render(scene,camera)}
function loop(now){requestAnimationFrame(loop);const dt=Math.min(.04,(now-last)/1000);last=now;if(state.running)flightPhysics(dt);state.radioAlt=state.altitude;drawPFD();drawND();drawEICAS();updateWarnings();monitorTutorial();renderView()}requestAnimationFrame(loop);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);if(tutorialActive)placeTutorial($(activeTutorialSteps()[tutorialIndex]?.target))});refreshChecklist();
