import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';

const mount=document.querySelector('#game');
const ui={speed:document.querySelector('#speed'),alt:document.querySelector('#altitude'),heading:document.querySelector('#heading'),start:document.querySelector('#start'),button:document.querySelector('#startButton'),startTitle:document.querySelector('#startTitle'),startText:document.querySelector('#startText'),record:document.querySelector('#record'),missionTitle:document.querySelector('#missionTitle'),missionText:document.querySelector('#missionText'),missionMeta:document.querySelector('#missionMeta')};
const RECORD_KEY='cloud-flight-record-v1';
let record=JSON.parse(localStorage.getItem(RECORD_KEY)||'{"bestScore":0,"landings":0}');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x82c6e8);scene.fog=new THREE.Fog(0x82c6e8,400,2900);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,6000);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;mount.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xe8f8ff,0x477138,2.2));const sun=new THREE.DirectionalLight(0xfff4d5,2.6);sun.position.set(-400,600,300);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(12000,12000),new THREE.MeshStandardMaterial({color:0x61884b,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const grid=new THREE.GridHelper(12000,240,0x8bb36c,0x7fa464);grid.position.y=.2;scene.add(grid);
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.55,metalness:.08})}function box(s,p,m){const z=new THREE.Mesh(new THREE.BoxGeometry(...s),m);z.position.set(...p);z.castShadow=true;return z}
function plane(){const g=new THREE.Group(),white=mat(0xf4f4ed),red=mat(0xb31d29),yellow=mat(0xf1bd2f),dark=mat(0x143b62),glass=mat(0x183f5b);const body=new THREE.Mesh(new THREE.CylinderGeometry(1.28,1.55,12,24),white);body.rotation.z=Math.PI/2;body.castShadow=true;g.add(body);const nose=new THREE.Mesh(new THREE.SphereGeometry(1.3,24,16),white);nose.scale.set(1.18,1,1);nose.position.x=6;g.add(nose);const tail=new THREE.Mesh(new THREE.ConeGeometry(1.25,3.4,24),white);tail.rotation.z=-Math.PI/2;tail.position.x=-7.3;g.add(tail);const stripe=box([8.5,.09,1.05],[0,1.48,0],red);stripe.rotation.z=Math.PI/2;g.add(stripe);const stripe2=box([2.6,.11,1.13],[3.2,1.5,0],yellow);stripe2.rotation.z=Math.PI/2;g.add(stripe2);const wing=new THREE.Mesh(new THREE.BoxGeometry(4.4,.16,13),white);wing.position.set(-.5,-.25,0);wing.castShadow=true;g.add(wing);const tailWing=new THREE.Mesh(new THREE.BoxGeometry(2,.12,5),white);tailWing.position.set(-5.8,.75,0);g.add(tailWing);const fin=new THREE.Mesh(new THREE.BoxGeometry(2.3,3.5,.18),red);fin.position.set(-6.3,2.35,0);fin.rotation.z=-.18;g.add(fin);g.add(box([.08,1.5,1.7],[-6.55,3.35,.13],yellow));for(const side of[-1,1]){const eng=new THREE.Mesh(new THREE.CylinderGeometry(.72,.88,2.6,20),dark);eng.rotation.z=Math.PI/2;eng.position.set(.2,-1.05,side*4.25);eng.castShadow=true;g.add(eng);const wheel=new THREE.Mesh(new THREE.TorusGeometry(.34,.1,8,16),mat(0x151515));wheel.rotation.y=Math.PI/2;wheel.position.set(-1,-1.8,side*.65);g.add(wheel)}for(let i=0;i<11;i++){g.add(box([.1,.35,.18],[3.6-i*.7,.65,1.3],glass));g.add(box([.1,.35,.18],[3.6-i*.7,.65,-1.3],glass))}return g}
const jet=plane();scene.add(jet);
const runway=new THREE.Group();const slab=new THREE.Mesh(new THREE.BoxGeometry(80,.35,1400),mat(0x42484b));slab.position.y=.25;runway.add(slab);for(let z=-620;z<=620;z+=55)runway.add(box([3,.12,27],[0,.48,z],mat(0xf7f5df)));runway.position.set(850,0,-2400);scene.add(runway);
const beacon=new THREE.Mesh(new THREE.TorusGeometry(18,1.4,10,36),mat(0xffd339));beacon.rotation.x=Math.PI/2;beacon.position.set(250,40,-700);scene.add(beacon);const beaconLight=new THREE.PointLight(0xffd339,4,260);beaconLight.position.copy(beacon.position);scene.add(beaconLight);
let fly=false,spd=280,alt=3200,heading=90,pitch=0,roll=0,keys={},drag=null,phase='beacon',flightStart=0;
function updateRecord(){ui.record.textContent=record.bestScore?`本机最佳：${record.bestScore} 分 · 已完成 ${record.landings} 次着陆`:'本机最佳：暂无记录';ui.missionMeta.textContent=record.bestScore?`最佳得分：${record.bestScore} · 完成着陆：${record.landings}`:'最佳得分：--'}
function reset(){spd=280;alt=3200;heading=90;pitch=0;roll=0;phase='beacon';jet.position.set(0,20+alt*.01,0);jet.rotation.set(0,Math.PI/2,0);beacon.visible=true;flightStart=performance.now()}
function update(){ui.speed.textContent=Math.round(spd);ui.alt.textContent=Math.round(alt);ui.heading.textContent=String((Math.round(heading)+360)%360).padStart(3,'0')+'°';if(phase==='beacon'){const d=jet.position.distanceTo(beacon.position);ui.missionTitle.textContent='任务 1 / 2：穿越航标';ui.missionText.textContent=`距黄色航标 ${Math.max(0,Math.round(d))} 米`;}else{const dx=jet.position.x-runway.position.x,dz=jet.position.z-runway.position.z;ui.missionTitle.textContent='任务 2 / 2：机场着陆';ui.missionText.textContent=`距跑道 ${Math.round(Math.hypot(dx,dz))} 米 · 保持低于 60 米并减速`;}}
function begin(){reset();fly=true;ui.start.classList.add('off')}
function finish(success){fly=false;const elapsed=(performance.now()-flightStart)/1000;if(success){const score=Math.max(100,Math.round(1400-elapsed*3-alt*.1-(spd-170)*2));record.bestScore=Math.max(record.bestScore,score);record.landings++;localStorage.setItem(RECORD_KEY,JSON.stringify(record));ui.startTitle.textContent='完美着陆！';ui.startText.textContent=`本次飞行得分 ${score} 分。${score===record.bestScore?'这是你的最佳纪录！':'再试一次，争取更平稳的进近。'}`;}else{ui.startTitle.textContent='飞行结束';ui.startText.textContent=phase==='beacon'?'飞机接触地面前尚未通过航标。':'着陆条件不足：请在跑道范围内以低高度、低速度进近。'}ui.button.textContent='重新起飞';updateRecord();ui.start.classList.remove('off')}
ui.button.addEventListener('click',begin);ui.button.addEventListener('pointerup',event=>{event.preventDefault();if(!fly)begin()});updateRecord();reset();
function animate(){requestAnimationFrame(animate);beacon.rotation.z+=.012;if(fly){let tr=(keys.a||keys.arrowleft?1:0)-(keys.d||keys.arrowright?1:0),li=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0);if(drag){tr=drag.x;li=drag.y}roll+=(tr*.55-roll)*.04;pitch+=(li*.3-pitch)*.04;heading+=roll*.65;alt=Math.max(0,alt+pitch*7);spd=Math.max(170,Math.min(430,spd+li*.8));const r=heading*Math.PI/180;jet.position.x+=Math.cos(r)*spd*.02;jet.position.z-=Math.sin(r)*spd*.02;jet.position.y=20+alt*.01;jet.rotation.y=-r+Math.PI/2;jet.rotation.z=-roll;jet.rotation.x=pitch;if(phase==='beacon'&&jet.position.distanceTo(beacon.position)<55){phase='landing';beacon.visible=false;beaconLight.intensity=0}if(alt<12){const onRunway=Math.abs(jet.position.x-runway.position.x)<42&&Math.abs(jet.position.z-runway.position.z)<700;finish(phase==='landing'&&onRunway&&spd<245)}update()}else{camera.position.lerp(new THREE.Vector3(42,55,55),.025);camera.lookAt(0,35,0)}const r=heading*Math.PI/180,desired=new THREE.Vector3(jet.position.x-45*Math.cos(r),jet.position.y+22,jet.position.z+45*Math.sin(r));if(fly){camera.position.lerp(desired,.04);camera.lookAt(jet.position.x+45*Math.cos(r),jet.position.y-3,jet.position.z-45*Math.sin(r))}renderer.render(scene,camera)}animate();update();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.startsWith('Arrow'))e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);renderer.domElement.addEventListener('pointerdown',e=>drag={x:(e.clientX/innerWidth-.5)*2,y:(.5-e.clientY/innerHeight)*2});renderer.domElement.addEventListener('pointermove',e=>{if(e.buttons)drag={x:(e.clientX/innerWidth-.5)*2,y:(.5-e.clientY/innerHeight)*2}});addEventListener('pointerup',()=>drag=null);
